<?php
error_reporting(0);
session_start();
include_once "../academic_sisfo1.php";
ViewHeaderApps("MASTER PENDAFTAR");

$lungo = (empty($_REQUEST['lungo']))? "fnEdit" : $_REQUEST['lungo'];
$lungo();

function fnEdit() {
	global $ci, $koneksi;
	$Institusi = AmbilOneField('identitas', 'Kode', KodeID, 'Nama');
	
	// hardcode
	//$_REQUEST['id'] = 0;
	//$_REQUEST['md'] = 1;
	
	$gel = sqling(@$_REQUEST['gel']);
	$md = $_REQUEST['md'] + 0;
	$id = $_REQUEST['id'];
	
	$g = $ci->pmbperiod_model->get_active(array( 'PMBPeriodID' => $gel ));
	if (empty($g) || $g['NA'] == 'Y') {
		die(PesanError("Error", "Gelombang tidak ditemukan atau sudah tidak aktif.<br />Hubungi Sysadmin untuk informasi lebih lanjut.<hr size=1 color=silver /><input type=button name='btnClose' value='Tutup' onClick='window.close()' />"));
	}
	
  if ($md == 0) {
    $w = AmbilFieldx('aplikan', "AplikanID='$id' and KodeID", KodeID, '*');
    if (empty($w)) die(PesanError('Error',
      "Data aplikan dengan nomer: <b>$id</b> tidak ditemukan.<br />
      Hubungi Sysadmin untuk informasi lebih lanjut.
      <hr size=1 color=silver />
      <input type=button name='btnClose' value='Tutup' onClick='window.close()' />"));
    $jdl = "Edit Data Aplikan - $w[PMBPeriodID]";
    $_id = "<font size=+1>$id</font>";
  } elseif ($md == 1) {
    $w = array();
    $w['TanggalLahir'] = date('Y-m-d');
    $w['TanggalBuat'] = date('Y-m-d');
    $w['TanggalEdit'] = date('Y-m-d');
	$w['Kelamin'] = 'P';
	$w['SudahBekerja'] = 'N';
    $jdl = "Tambah Data Aplikan - ".$g['PMBPeriodID'];
    $_id = "<font color=red>[ Autogenerated ]</font>";
  } else {
	die(PesanError("Error", "Mode edit <b>$md</b> tidak dikenali oleh sistem.<br />Hubungi Sysadmin untuk informasi lebih lanjut. <hr size=1 color=silver /> <input type=button name='btnClose' value='Tutup' onClick='window.close()' />"));
  }
  
  // replace title
  $jdl = 'Biodata Pendaftar';
  
  echo <<<ESD
  <SCRIPT LANGUAGE="JavaScript1.2">
  <!--
  function carisekolah(frm){
    lnk = "carisekolah.php?SekolahID="+frm.AsalSekolah.value+"&Cari="+frm.NamaSekolah.value;
	win2 = window.open(lnk, "", "width=350, top=150, left=450 height=350, scrollbars, status");
    win2.creator = frm;
  }
  function caript(frm){
    lnk = "cariperguruantinggi.php?SekolahID="+frm.AsalSekolah.value+"&Cari="+frm.NamaSekolah.value;
	win2 = window.open(lnk, "", "width=350, top=150, left=450 height=350, scrollbars, status");
    win2.creator = frm;
  }
  function tambahsekolah(frm) {
	lnk = "pmbasalsek.edit.php?md=1";
	win2 = window.open(lnk, "", "width=600, height=600, scrollbars, status");
    win2.creator = self;
  }
  function tambahpt(frm) {
	lnk = "pmbasalpt.edit.php?md=1";
	win2 = window.open(lnk, "", "width=600, height=600, scrollbars, status");
    win2.creator = self;
  }
  function ChooseThis(name, target)
  {	var count = data.JumlahSumberInfo.value;
	if(document.getElementById(name+target).checked == true)
	{	for(var i = 0; i < count; i++)
		{	document.getElementById(name+i).checked = false;
		}
		document.getElementById(name+target).checked = true;
	}
  }
  -->
  </script>
ESD;

  
  // Parameter
  $NamaSekolah = AmbilOneField('asalsekolah', 'SekolahID', @$w['AsalSekolah'], "concat(Nama, ', ', Kota)");
  $optkelamin = AmbilRadio("select Kelamin, Nama, concat(Kelamin, ' - ', Nama) as _kel from kelamin where NA='N'",
    'Kelamin', "_kel", 'Kelamin', @$w[Kelamin], ', ');
  $TanggalLahir = AmbilComboTgl($w['TanggalLahir'], 'TGL');
  $TanggalDaftar = AmbilComboTgl($w['TanggalEdit'], 'TGLBuat');
  $optagama = AmbilCombo2('agama', "concat(Agama, ' - ', Nama)", 'Agama', @$w['Agama'], '', 'Agama');
  $optpendidikan = AmbilCombo2('pendidikanortu', 'Nama', 'Pendidikan', @$w['PendidikanAyah'], '', 'Pendidikan');
  $optpekerjaan = AmbilCombo2('pekerjaanortu', 'Nama', 'Nama', @$w['PekerjaanAyah'], '', 'Pekerjaan');
  $SumberInformasi = GetSumberInformasi(@$w['SumberInformasi']);
  $PilihanProgram = AmbilCombo2('program', "concat(ProgramID, ' - ', Nama)", 'ProgramID', @$w['ProgramID'], '', 'ProgramID');
  $sudahbekerjachecked = (@$w['SudahBekerja'] == 'Y')? 'checked' : '';
  
  // presenter
  if (isset($_SESSION['username']) && !empty($_SESSION['username'])) {
	$optpresenter = AmbilCombo2('presenter', "concat(PresenterID, ' - ', Nama)", 'PresenterID', @$w['PresenterID'], '', 'PresenterID');
  } else {
	$optpresenter = '<option value="132" seleceted>132 - Web</option>';
  }
  
  // Tampilkan
  CheckFormScript("PresenterID,Program,Nama,Kelamin,AsalSekolah,TahunLulus,NilaiSekolah,TempatLahir");
  
  // make sure variable exist
  $w['CatatanPresenter'] = (isset($w['CatatanPresenter'])) ? $w['CatatanPresenter'] : '';
  $w['Nama'] = (isset($w['Nama'])) ? $w['Nama'] : '';
  $w['TempatLahir'] = (isset($w['TempatLahir'])) ? $w['TempatLahir'] : '';
  $w['Alamat'] = (isset($w['Alamat'])) ? $w['Alamat'] : '';
  $w['Kota'] = (isset($w['Kota'])) ? $w['Kota'] : '';
  $w['Propinsi'] = (isset($w['Propinsi'])) ? $w['Propinsi'] : '';
  $w['KodePos'] = (isset($w['KodePos'])) ? $w['KodePos'] : '';
  $w['RT'] = (isset($w['RT'])) ? $w['RT'] : '';
  $w['RW'] = (isset($w['RW'])) ? $w['RW'] : '';
  $w['Telepon'] = (isset($w['Telepon'])) ? $w['Telepon'] : '';
  $w['Handphone'] = (isset($w['Handphone'])) ? $w['Handphone'] : '';
  $w['Email'] = (isset($w['Email'])) ? $w['Email'] : '';
  $w['AsalSekolah'] = (isset($w['AsalSekolah'])) ? $w['AsalSekolah'] : '';
  $w['AlamatSekolah'] = (isset($w['AlamatSekolah'])) ? $w['AlamatSekolah'] : '';
  $w['JurusanSekolah'] = (isset($w['JurusanSekolah'])) ? $w['JurusanSekolah'] : '';
  $w['TahunLulus'] = (isset($w['TahunLulus'])) ? $w['TahunLulus'] : '';
  $w['NilaiSekolah'] = (isset($w['NilaiSekolah'])) ? $w['NilaiSekolah'] : '';
  $w['ProdiID'] = (isset($w['ProdiID'])) ? $w['ProdiID'] : '';
  $w['NamaAyah'] = (isset($w['NamaAyah'])) ? $w['NamaAyah'] : '';
  $w['Catatan'] = (isset($w['Catatan'])) ? $w['Catatan'] : '';
  
  echo <<<ESD
  <table class=bsc cellspacing=1 width=100% />
  <form name='data' action='?' method=POST onSubmit="return CheckForm(this)">
  <input type=hidden name='lungo' value='fnSave' />
  <input type=hidden name='md' value='$md' />
  <input type=hidden name='gel' value='$g[PMBPeriodID]' />
  <input type=hidden name='id' value='$id' />
  
  <tr><th class=ttl colspan=2>$jdl</th></tr>
  <tr><td class=ul1>Nomer Aplikan :</td>
	  <td class=ul1>$_id</td>
      </tr>
  <tr><td class=ul1>Tanggal Daftar :</td>
      <td class=ul1>$TanggalDaftar</td>
      </tr>
  <tr><td class=ul1>Presenter: </td>
	  <td class=ul1><select name='PresenterID'>$optpresenter</select></td>
	  </tr>
  <tr style="display: none;"><td class=ul1>Catatan Presenter: </td>
	  <td class=ul1>
      <textarea name='CatatanPresenter' cols=30 rows=3>$w[CatatanPresenter]</textarea>
      </td>
  <tr><td bgcolor=green colspan=2 height=1></td></tr>
  
  <tr><td class=ul1>Nama :</td>
      <td class=ul1>
      <input type=text name='Nama' value='$w[Nama]' size=30 maxlength=50 />
      </td>
      </tr>
  <tr><td class=ul1>Jenis Kelamin :</td>
      <td class=ul1>$optkelamin</td>
      </tr>
  <tr><td class=ul1>Tempat Lahir :</td>
      <td class=ul1>
      <input type=text name='TempatLahir' value='$w[TempatLahir]' size=30 maxlength=50 />
      </td>
      </tr>
  <tr><td class=ul1>Tanggal Lahir :</td>
      <td class=ul1>
      $TanggalLahir
      </td>
      </tr>
  <tr><td class=ul1>Alamat :</td>
      <td class=ul1>
      <input type=text name='Alamat' value='$w[Alamat]' size=40 maxlength=200 />
      </td>
      </tr>
  <tr><td class=ul1>Kota :</td>
      <td class=ul1>
      <input type=text name='Kota' value='$w[Kota]' size=30 maxlength=50 /> 
      </tr>
  <tr><td class=ul1>Propinsi/Kode Pos: </td>
      <td class=ul1>
	  <input type=text name='Propinsi' value='$w[Propinsi]' size=30 maxlength=50 />/
      <input type=text name='KodePos' value='$w[KodePos]' size=10 maxlength=50 />
      </td>
      </tr>
  <tr><td class=ul1>RT / RW :</td>
      <td class=ul1>
      <input type=text name='RT' value='$w[RT]' size=5 maxlength=5 /> /
      <input type=text name='RW' value='$w[RW]' size=5 maxlength=5 />
      </td>
      </tr>
  <tr><td class=ul1>Telepon / Ponsel :</td>
      <td class=ul1>
      <input type=text name='Telepon' value='$w[Telepon]' size=20 maxlength=50 /> /
      <input type=text name='Handphone' value='$w[Handphone]' size=20 maxlength=50 />
      </td>
      </tr>
  <tr><td class=ul1>E-mail :</td>
      <td class=ul1>
      <input type=text name='Email' value='$w[Email]' size=40 maxlength=50 />
      </td>
      </tr>
  
  <tr><th class=ttl colspan=2>Pendidikan Terakhir</th></tr>
  <tr><td class=ul1>ID Sekolah :</td>
      <td class=ul1>
		<input type='text' name='AsalSekolah' value='$w[AsalSekolah]' size=20 maxlength=50 disabled>
		<input type='hidden' name='SavAsalSekolah' value='$w[AsalSekolah]' ></td>
	  </tr>
  <tr><td class=ul1>Nama Sekolah :</td>
	  <td class=ul1><input type=text name='NamaSekolah' value='$NamaSekolah' size=50 maxlength=255>
	  <br><input type="button" onClick="javascript:data.AsalSekolah.value='';data.NamaSekolah.value='';" value="Reset" />
		<input type="button" onClick='javascript:carisekolah(data)' value="Cari Sekolah" />
		<input type="button" onClick='javascript:caript(data)' value="Cari Perguruan Tinggi" />
		<!--
		<input type="button" onClick='javascript:tambahsekolah(data)' value="Tambah Institusi" />
		-->
		<br /><br />
	    <div class="info"><b>TIPS</b>
		<ul>
		<li>Masukkan <b>nama sekolah parsial</b> diikuti dengan <b>tanda koma</b> dan <b>nama kota</b> di mana sekolah terebut berada. <br \>
			Contoh: 'Budi Utomo, Jakarta' ATAU 'Negeri 1, Surabaya'.
		</li>
		<li><b>Hindari penggunaan kata-kata umum</b>, seperti SMA, SMU, SLTA, SEKOLAH, SCHOOL, dll. <br \>
					  Gunakan kata-kata yang dapat mengidentifikasi sekolah yang dicari secara unik.
		</li>
		</ul>
		</div>
		
		</td></tr>
      </tr>
  <tr><td class=ul1>Alamat Sekolah:</td>
	  <td class=ul1><input type=text name='AlamatSekolah' value='$w[AlamatSekolah]' size=50 maxlength=255>
  <tr><td class=ul1>Jurusan Sekolah :</td>
      <td class=ul1>
      <input type=text name='JurusanSekolah' value='$w[JurusanSekolah]' size=40 maxlength=50 />
      </td>
      </tr>
      
  <tr><td class=ul1>Tahun Lulus :</td>
      <td class=ul1>
      <input type=text name='TahunLulus' value='$w[TahunLulus]' size=5 maxlength=5 />
      </td>
  <tr><td class=ul1>Nilai UAN :</td>
      <td class=ul1>
      <input type=text name='NilaiSekolah' value='$w[NilaiSekolah]' size=5 maxlength=5 />
      </td>
      </tr>
  <tr><td class=ul1>Sudah Bekerja?</td>
	  <td class=ul1>
			<input type=checkbox name='SudahBekerja' value='Y' $sudahbekerjachecked>
      </td>
  </tr>
	  
  <tr><th class=ttl colspan=2>Data Orangtua/Wali</th></tr>
  <tr><td class=ul1>Nama Orangtua/Wali :</td>
      <td class=ul1>
      <input type=text name='NamaAyah' value='$w[NamaAyah]' size=30 maxlength=50 />
      </td>
      </tr>
  <tr><td class=ul1>Pendidikan Terakhir :</td>
      <td class=ul1>
      <select name='PendidikanAyah'>$optpendidikan</select>
      </td>
      </tr>
  <tr><td class=ul1>Pekerjaan :</td>
      <td class=ul1>
      <select name='PekerjaanAyah'>$optpekerjaan</select>
      </td>
      </tr>

  <tr><th class=ttl colspan=2>Pilihan Program Studi</th></tr>
ESD;
  
  $s1 = "select DISTINCT(j.JenjangID), j.Nama, j.Keterangan 
			from prodi p left outer join jenjang j on p.JenjangID=j.JenjangID
			where p.KodeID='".KodeID."' and p.NA='N' order by p.JenjangID DESC" ;
  $r1 = mysqli_query($koneksi, $s1);
  
  $_Jenjang = "928rlaisfav9sfap";
  while($w1 = mysqli_fetch_array($r1))
  {	
	$Pilihan = GetPilihanProdi($w1['JenjangID'], $w['ProdiID']);
	echo "<tr><td class=ul1>&bull; $w1[Keterangan] ($w1[Nama]) :</td>
			  <td class=ul1>$Pilihan</td>
			  </tr>";
	
  }

  echo <<<ESD
  <tr><td class=ul1>Program : </td>
	  <td class=ul1><select name='Program'>$PilihanProgram</select></td>
	  </tr>
  
  <tr><td class=ul1 valign=top>
      Atas inisiatif siapa Sdr/i datang ke<br />$Institusi?
      </td>
      <td class=ul1>
      <textarea name='Catatan' cols=30 rows=3>$w[Catatan]</textarea>
      </td>
      </tr>
  
  <tr><td class=ul1 valign=top>Sumber Informasi :</td>
      <td class=ul1>
      $SumberInformasi
      </td>
      </tr>
  
  <tr><td class=ul1 colspan=2 align=center>
      <input type=submit name='btnSimpan' value='Simpan' />
      <input type=button name='btnBatal' value='Batal'
        onClick="window.close()" />
      </td>
      </tr>
  </form>
  </table>
ESD;
}

function GetSumberInformasi($nilai) {
	global $koneksi;
  $arrnilai = explode(',', $nilai);
  $ret = '';
  $s = "select * from sumberinfo where KodeID='".KodeID."' and NA='N' order by InfoID";
  $r = mysqli_query($koneksi, $s);
  $n = 0;
  while ($w = mysqli_fetch_array($r)) {
    $ck = (array_search($w['InfoID'], $arrnilai) === false)? '' : 'checked';
    $ret .= "<input type=checkbox id='sumberinfo$n' name='sumberinfo[]' value='$w[InfoID]' $ck> $w[Nama]<br />";
	$n++;
  }
  $ret .="<input type=hidden name='JumlahSumberInfo' value='$n'>";
  return $ret;
}

function GetPilihanProdi($jen, $pil) {
	global $koneksi;
  $arr = explode(',', $pil);
  $ret = array();
  $s = "select ProdiID, Nama from prodi where KodeID='".KodeID."' and JenjangID='$jen' and NA='N' order by ProdiID";
  $r = mysqli_query($koneksi, $s);
  while ($w = mysqli_fetch_array($r)) {
    $ck = (array_search($w['ProdiID'], $arr) === false)? '' : 'checked';
    $ret[] = "<input type=checkbox name='Pilihan[]' value='$w[ProdiID]' $ck> $w[Nama]";
  }
  $_ret = implode('&nbsp;&nbsp;', $ret);
  return $_ret;
}

function fnSave() {
	global $koneksi;
  include_once "statusaplikan.lib.php";
  
  $md = $_REQUEST['md']+0;
  $id = $_REQUEST['id'];
  $gel = sqling($_REQUEST['gel']);
  
  $AplikanID = $id;
  
  if($md==1)
	{ 
	  $AplikanID = GetNextAplikanID($gel);
  
	  $ada = AmbilOneField('aplikan', "KodeID='".KodeID."' and AplikanID", $AplikanID, 'AplikanID');
     
	  if (!empty($ada)) 
	  {
        die(PesanError('Error',
          "Nomer Aplikan sudah ada.<br />
          Anda harus memasukkan nomer Aplikan yang lain.<br />
          Hubungi Sysadmin untuk informasi lebih lanjut.
          <hr size=1 color=silver />
          Opsi: <input type=button name='Kembali' value='Kembali'
            onClick=\"javascript:history.go(-1)\" />
            <input type=button name='Tutup' value='Tutup'
            onClick=\"window.close()\" />"));
      }	  
	}
  $PresenterID = $_REQUEST['PresenterID'];
  $CatatanPresenter = sqling($_REQUEST['CatatanPresenter']);
  $Nama = sqling($_REQUEST['Nama']);
  $Kelamin = sqling($_REQUEST['Kelamin']);
  $TempatLahir = sqling($_REQUEST['TempatLahir']);
  $TanggalLahir = "$_REQUEST[TGL_y]-$_REQUEST[TGL_m]-$_REQUEST[TGL_d]";
  $TGLBuat = "$_REQUEST[TGLBuat_y]-$_REQUEST[TGLBuat_m]-$_REQUEST[TGLBuat_d]";
  $Agama = sqling($_REQUEST['Agama']);
  $Alamat = sqling($_REQUEST['Alamat']);
  $Kota = sqling($_REQUEST['Kota']);
  $Propinsi = sqling($_REQUEST['Propinsi']);
  $KodePos = sqling($_REQUEST['KodePos']);
  $RT = sqling($_REQUEST['RT']);
  $RW = sqling($_REQUEST['RW']);
  $Telepon = sqling($_REQUEST['Telepon']);
  $Handphone = sqling($_REQUEST['Handphone']);
  $Email = sqling($_REQUEST['Handphone']);
  $AsalSekolah = sqling($_REQUEST['SavAsalSekolah']);
  $AlamatSekolah = $_REQUEST['AlamatSekolah'];
  $JurusanSekolah = sqling($_REQUEST['JurusanSekolah']);
  $TahunLulus = sqling($_REQUEST['TahunLulus']);
  $SudahBekerja = (!empty($_REQUEST['SudahBekerja']))? 'Y' : 'N';
  $NilaiSekolah = $_REQUEST['NilaiSekolah'];
  $NamaAyah = sqling($_REQUEST['NamaAyah']);
  $PendidikanAyah = sqling($_REQUEST['PendidikanAyah']);
  $PekerjaanAyah = sqling($_REQUEST['PekerjaanAyah']);
  $Program = $_REQUEST['Program'];
  $Catatan = sqling($_REQUEST['Catatan']);
  $SumberInfo = implode(',', $_REQUEST['sumberinfo']);
  // Simpan
  $Pilihan = $_REQUEST['Pilihan'];
  $ProdiID = "";
  foreach($Pilihan as $prodi)
  {	$ProdiID .= (empty($ProdiID))? $prodi : ','.$prodi;
  }
  
  if ($md == 0) {
    $s = "update aplikan
      set PresenterID = '$PresenterID', CatatanPresenter = '$CatatanPresenter', AplikanID = '$AplikanID', 
		  Nama = '$Nama', Kelamin = '$Kelamin', TempatLahir = '$TempatLahir', TanggalLahir = '$TanggalLahir',
          Agama = '$Agama', Alamat = '$Alamat', Kota = '$Kota', Propinsi = '$Propinsi', KodePos = '$KodePos', RT = '$RT', RW = '$RW',
          Telepon = '$Telepon', Handphone = '$Handphone', Email = '$Email',
          AsalSekolah = '$AsalSekolah', AlamatSekolah='$AlamatSekolah', JurusanSekolah = '$JurusanSekolah', TahunLulus = '$TahunLulus', 
		  SudahBekerja = '$SudahBekerja', NilaiSekolah = '$NilaiSekolah',
          NamaAyah = '$NamaAyah', PendidikanAyah = '$PendidikanAyah', PekerjaanAyah = '$PekerjaanAyah',
          ProdiID='$ProdiID', ProgramID = '$Program', 
          Catatan = '$Catatan', SumberInformasi = '$SumberInfo',
          LoginEdit = '$_SESSION[_Login]', TanggalEdit = '$TGLBuat'
      where AplikanID = '$id' ";
    $r = mysqli_query($koneksi, $s);
	
	SetStatusAplikan('APL', $AplikanID, $gel);
	
    TutupScript();
  }
  elseif ($md == 1) {
	
	$s = "insert into aplikan
      (KodeID, PMBPeriodID,  PresenterID, AplikanID, CatatanPresenter, 
      Nama, Kelamin, TempatLahir, TanggalLahir,
      Agama, Alamat, Kota, Propinsi, KodePos, RT, RW,
      Telepon, Handphone, Email,
      AsalSekolah, AlamatSekolah, JurusanSekolah, TahunLulus, 
	  SudahBekerja, NilaiSekolah, 
      NamaAyah, PendidikanAyah, PekerjaanAyah,
      ProdiID, ProgramID, 
      Catatan, SumberInformasi,
	  Login, Password, 
      LoginBuat, TanggalBuat, TanggalEdit)
      values
      ('".KodeID."', '$gel', '$PresenterID', '$AplikanID', '$CatatanPresenter', 
      '$Nama', '$Kelamin', '$TempatLahir', '$TanggalLahir',
      '$Agama', '$Alamat', '$Kota', '$Propinsi', '$KodePos', '$RT', '$RW',
      '$Telepon', '$Handphone', '$Email',
      '$AsalSekolah', '$AlamatSekolah', '$JurusanSekolah', '$TahunLulus', 
	  '$SudahBekerja', '$NilaiSekolah',
      '$NamaAyah', '$PendidikanAyah', '$PekerjaanAyah',
      '$ProdiID', '$Program',
      '$Catatan', '$SumberInfo',
	  '$AplikanID', PASSWORD('$TanggalLahir'),
      '$_SESSION[_Login]', now(), '$TGLBuat')";
    $r = mysqli_query($koneksi, $s);
	
	SetStatusAplikan('APL', $AplikanID, $gel);
    
	TutupScript();
  }
  else die(PesanError('Error',
    "Mode edit <b>$md</b> tidak dikenali sistem.<br />
    Hubungi Sysadmin untuk informasi lebih lanjut.
    <hr size=1 color=silver />
    <input type=button name='btnClose' value='Tutup' onClick='window.close()' />"));
	
}

function TutupScript() {
echo <<<SCR
<h2 style="padding: 20px 0; text-align: center;">Selamat Pendaftaran Anda sudah selesai.</h2>
<SCRIPT>
  function ttutup() {
    opener.location='../index.php?ndelox=$_SESSION[ndelox]&_apliPage=0';
    self.close();
    return false;
  }
  ttutup();
</SCRIPT>
SCR;
}

function GetNextAplikanID($gel) {
  $gelombang = AmbilFieldx('pmbperiod', "PMBPeriodID='$gel' and KodeID", KodeID, "FormatNoAplikan, DigitNoAplikan");
  // Buat nomer baru
  $nomer = str_pad('', $gelombang['DigitNoAplikan'], '_', STR_PAD_LEFT);
  $nomer = $gelombang['FormatNoAplikan'].$nomer;
  $akhir = AmbilOneField('aplikan',
    "AplikanID like '$nomer' and KodeID", KodeID, "max(AplikanID)");
  $nmr = str_replace($gelombang['FormatNoAplikan'], '', $akhir);
  $nmr++;
  $baru = str_pad($nmr, $gelombang['DigitNoAplikan'], '0', STR_PAD_LEFT);
  $baru = $gelombang['FormatNoAplikan'].$baru;
  return $baru;
}
?>

</body>
</html>
